service: hub-travel-functions

provider:
  name: aws
  runtime: java11
  stage: dev
  region: sa-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"

package:
  artifact: target/hub-travel-functions-0.0.1-SNAPSHOT.jar

functions:
  CreateExcursionHandler:
    handler: br.com.yes.handler.excursion.BookedExcursionHandler
    events:
      - http:
          path: /excursions
          method: post
          cors: true

  RegisterAgencyHandler:
    handler: br.com.yes.handler.agency.RegisterAgencyHandler
    events:
      - http:
          path: /agencies
          method: post
          cors: true

  UpdatePartnerListHandler:
    handler: br.com.yes.handler.agency.UpdatePartnerListHandler
    events:
      - http:
          path: /agencies/{agencyId}/partner
          method: put
          cors: true
          request:
            parameters:
              paths:
                agencyId: true

  FindAgencyByIdHandler:
    handler: br.com.yes.handler.agency.FindAgencyByIdHandler
    events:
      - http:
          path: /agencies/{agencyId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                agencyId: true

  FindAllAgenciesHandler:
    handler: br.com.yes.handler.agency.FindAllAgenciesHandler
    events:
      - http:
          path: /agencies
          method: get
          cors: true
          request:
            parameters:
              paths:
                agencyId: true

  FindAllExcursionOrderedByPartners:
    handler: br.com.yes.handler.excursion.FindAllExcursionOrderedByPartners
    events:
      - http:
          path: /agencies/{agencyId}/partner/excursions
          method: get
          cors: true
          request:
            parameters:
              paths:
                agencyId: true

  UploadDataSearchEngineHandler:
    handler: br.com.yes.handler.excursion.UploadDataSearchEngineHandler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::ImportValue: hub-travel-stack-dev-Excursion-StreamArn
